"""initial schema

Revision ID: 001
Revises:
Create Date: 2026-04-03 16:01:44.465841

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("po_number", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("po_date", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("vendor_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("vendor_contact", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("requester_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "requester_department", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("line_items", sa.JSON(), nullable=True),
        sa.Column("total_amount", sa.Float(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("delivery_date", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("payment_terms", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("original_filename", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("sender_email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "batch_email_message_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_purchase_orders_created_at", "purchase_orders", ["created_at"], unique=False
    )
    op.create_index("ix_purchase_orders_status", "purchase_orders", ["status"], unique=False)
    op.create_index("ix_purchase_orders_batch_id", "purchase_orders", ["batch_id"], unique=False)
    op.create_table(
        "email_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("direction", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("email_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_email_logs_order_id", "email_logs", ["order_id"], unique=False)
    op.create_table(
        "issue_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("tag", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_issue_tags_order_id", "issue_tags", ["order_id"], unique=False)
    op.create_table(
        "processing_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("step", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_processing_logs_order_id", "processing_logs", ["order_id"], unique=False)
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_review_decisions_order_id", "review_decisions", ["order_id"], unique=False)
    op.create_table(
        "validation_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("check_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("result", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_validation_checks_order_id", "validation_checks", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_validation_checks_order_id", table_name="validation_checks")
    op.drop_table("validation_checks")
    op.drop_index("ix_review_decisions_order_id", table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index("ix_processing_logs_order_id", table_name="processing_logs")
    op.drop_table("processing_logs")
    op.drop_index("ix_issue_tags_order_id", table_name="issue_tags")
    op.drop_table("issue_tags")
    op.drop_index("ix_email_logs_order_id", table_name="email_logs")
    op.drop_table("email_logs")
    op.drop_index("ix_purchase_orders_batch_id", table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_status", table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_created_at", table_name="purchase_orders")
    op.drop_table("purchase_orders")
    # ### end Alembic commands ###
